"""Certified-reference candidate for problem 27.

The complete formulation is explicit below.  It contains no gold objective or hidden
mutation/certification information.
"""
import gurobipy as gp
from gurobipy import GRB


VARIABLE_SPECS = [{'name': 'x_1_2', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_1_3', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_1_4', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_1_5', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_1_6', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_1_7', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_2_1', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_2_3', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_2_4', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_2_5', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_2_6', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_2_7', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_3_1', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_3_2', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_3_4', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_3_5', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_3_6', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_3_7', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_4_1', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_4_2', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_4_3', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_4_5', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_4_6', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_4_7', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_5_1', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_5_2', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_5_3', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_5_4', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_5_6', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_5_7', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_6_1', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_6_2', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_6_3', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_6_4', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_6_5', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_6_7', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_7_1', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_7_2', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_7_3', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_7_4', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_7_5', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'x_7_6', 'vtype': 'B', 'lb': 0.0, 'ub': 1.0},
 {'name': 'u_2', 'vtype': 'I', 'lb': 0.0, 'ub': None},
 {'name': 'u_3', 'vtype': 'I', 'lb': 0.0, 'ub': None},
 {'name': 'u_4', 'vtype': 'I', 'lb': 0.0, 'ub': None},
 {'name': 'u_5', 'vtype': 'I', 'lb': 0.0, 'ub': None},
 {'name': 'u_6', 'vtype': 'I', 'lb': 0.0, 'ub': None},
 {'name': 'u_7', 'vtype': 'I', 'lb': 0.0, 'ub': None}]

CONSTRAINT_SPECS = [{'name': 'constraint_001',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_2', 1), ('x_1_3', 1), ('x_1_4', 1), ('x_1_5', 1), ('x_1_6', 1), ('x_1_7', 1)]},
 {'name': 'constraint_002',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_2_1', 1), ('x_2_3', 1), ('x_2_4', 1), ('x_2_5', 1), ('x_2_6', 1), ('x_2_7', 1)]},
 {'name': 'constraint_003',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_3_1', 1), ('x_3_2', 1), ('x_3_4', 1), ('x_3_5', 1), ('x_3_6', 1), ('x_3_7', 1)]},
 {'name': 'constraint_004',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_4_1', 1), ('x_4_2', 1), ('x_4_3', 1), ('x_4_5', 1), ('x_4_6', 1), ('x_4_7', 1)]},
 {'name': 'constraint_005',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_5_1', 1), ('x_5_2', 1), ('x_5_3', 1), ('x_5_4', 1), ('x_5_6', 1), ('x_5_7', 1)]},
 {'name': 'constraint_006',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_6_1', 1), ('x_6_2', 1), ('x_6_3', 1), ('x_6_4', 1), ('x_6_5', 1), ('x_6_7', 1)]},
 {'name': 'constraint_007',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_7_1', 1), ('x_7_2', 1), ('x_7_3', 1), ('x_7_4', 1), ('x_7_5', 1), ('x_7_6', 1)]},
 {'name': 'constraint_008',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_2_1', 1), ('x_3_1', 1), ('x_4_1', 1), ('x_5_1', 1), ('x_6_1', 1), ('x_7_1', 1)]},
 {'name': 'constraint_009',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_2', 1), ('x_3_2', 1), ('x_4_2', 1), ('x_5_2', 1), ('x_6_2', 1), ('x_7_2', 1)]},
 {'name': 'constraint_010',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_3', 1), ('x_2_3', 1), ('x_4_3', 1), ('x_5_3', 1), ('x_6_3', 1), ('x_7_3', 1)]},
 {'name': 'constraint_011',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_4', 1), ('x_2_4', 1), ('x_3_4', 1), ('x_5_4', 1), ('x_6_4', 1), ('x_7_4', 1)]},
 {'name': 'constraint_012',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_5', 1), ('x_2_5', 1), ('x_3_5', 1), ('x_4_5', 1), ('x_6_5', 1), ('x_7_5', 1)]},
 {'name': 'constraint_013',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_6', 1), ('x_2_6', 1), ('x_3_6', 1), ('x_4_6', 1), ('x_5_6', 1), ('x_7_6', 1)]},
 {'name': 'constraint_014',
  'sense': '==',
  'rhs': 1,
  'terms': [('x_1_7', 1), ('x_2_7', 1), ('x_3_7', 1), ('x_4_7', 1), ('x_5_7', 1), ('x_6_7', 1)]},
 {'name': 'constraint_015', 'sense': '>=', 'rhs': 1, 'terms': [('u_2', 1)]},
 {'name': 'constraint_016', 'sense': '<=', 'rhs': 6, 'terms': [('u_2', 1)]},
 {'name': 'constraint_017', 'sense': '>=', 'rhs': 1, 'terms': [('u_3', 1)]},
 {'name': 'constraint_018', 'sense': '<=', 'rhs': 6, 'terms': [('u_3', 1)]},
 {'name': 'constraint_019', 'sense': '>=', 'rhs': 1, 'terms': [('u_4', 1)]},
 {'name': 'constraint_020', 'sense': '<=', 'rhs': 6, 'terms': [('u_4', 1)]},
 {'name': 'constraint_021', 'sense': '>=', 'rhs': 1, 'terms': [('u_5', 1)]},
 {'name': 'constraint_022', 'sense': '<=', 'rhs': 6, 'terms': [('u_5', 1)]},
 {'name': 'constraint_023', 'sense': '>=', 'rhs': 1, 'terms': [('u_6', 1)]},
 {'name': 'constraint_024', 'sense': '<=', 'rhs': 6, 'terms': [('u_6', 1)]},
 {'name': 'constraint_025', 'sense': '>=', 'rhs': 1, 'terms': [('u_7', 1)]},
 {'name': 'constraint_026', 'sense': '<=', 'rhs': 6, 'terms': [('u_7', 1)]},
 {'name': 'constraint_027',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_2', 1), ('u_3', -1), ('x_2_3', 7)]},
 {'name': 'constraint_028',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_2', 1), ('u_4', -1), ('x_2_4', 7)]},
 {'name': 'constraint_029',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_2', 1), ('u_5', -1), ('x_2_5', 7)]},
 {'name': 'constraint_030',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_2', 1), ('u_6', -1), ('x_2_6', 7)]},
 {'name': 'constraint_031',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_2', 1), ('u_7', -1), ('x_2_7', 7)]},
 {'name': 'constraint_032',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_3', 1), ('u_2', -1), ('x_3_2', 7)]},
 {'name': 'constraint_033',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_3', 1), ('u_4', -1), ('x_3_4', 7)]},
 {'name': 'constraint_034',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_3', 1), ('u_5', -1), ('x_3_5', 7)]},
 {'name': 'constraint_035',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_3', 1), ('u_6', -1), ('x_3_6', 7)]},
 {'name': 'constraint_036',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_3', 1), ('u_7', -1), ('x_3_7', 7)]},
 {'name': 'constraint_037',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_4', 1), ('u_2', -1), ('x_4_2', 7)]},
 {'name': 'constraint_038',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_4', 1), ('u_3', -1), ('x_4_3', 7)]},
 {'name': 'constraint_039',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_4', 1), ('u_5', -1), ('x_4_5', 7)]},
 {'name': 'constraint_040',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_4', 1), ('u_6', -1), ('x_4_6', 7)]},
 {'name': 'constraint_041',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_4', 1), ('u_7', -1), ('x_4_7', 7)]},
 {'name': 'constraint_042',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_5', 1), ('u_2', -1), ('x_5_2', 7)]},
 {'name': 'constraint_043',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_5', 1), ('u_3', -1), ('x_5_3', 7)]},
 {'name': 'constraint_044',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_5', 1), ('u_4', -1), ('x_5_4', 7)]},
 {'name': 'constraint_045',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_5', 1), ('u_6', -1), ('x_5_6', 7)]},
 {'name': 'constraint_046',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_5', 1), ('u_7', -1), ('x_5_7', 7)]},
 {'name': 'constraint_047',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_6', 1), ('u_2', -1), ('x_6_2', 7)]},
 {'name': 'constraint_048',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_6', 1), ('u_3', -1), ('x_6_3', 7)]},
 {'name': 'constraint_049',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_6', 1), ('u_4', -1), ('x_6_4', 7)]},
 {'name': 'constraint_050',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_6', 1), ('u_5', -1), ('x_6_5', 7)]},
 {'name': 'constraint_051',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_6', 1), ('u_7', -1), ('x_6_7', 7)]},
 {'name': 'constraint_052',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_7', 1), ('u_2', -1), ('x_7_2', 7)]},
 {'name': 'constraint_053',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_7', 1), ('u_3', -1), ('x_7_3', 7)]},
 {'name': 'constraint_054',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_7', 1), ('u_4', -1), ('x_7_4', 7)]},
 {'name': 'constraint_055',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_7', 1), ('u_5', -1), ('x_7_5', 7)]},
 {'name': 'constraint_056',
  'sense': '<=',
  'rhs': 6,
  'terms': [('u_7', 1), ('u_6', -1), ('x_7_6', 7)]}]

OBJECTIVE_TERMS = [('x_1_2', 86),
 ('x_1_3', 49),
 ('x_1_4', 57),
 ('x_1_5', 31),
 ('x_1_6', 69),
 ('x_1_7', 50),
 ('x_2_1', 86),
 ('x_2_3', 68),
 ('x_2_4', 79),
 ('x_2_5', 93),
 ('x_2_6', 24),
 ('x_2_7', 5),
 ('x_3_1', 49),
 ('x_3_2', 68),
 ('x_3_4', 16),
 ('x_3_5', 7),
 ('x_3_6', 72),
 ('x_3_7', 67),
 ('x_4_1', 57),
 ('x_4_2', 79),
 ('x_4_3', 16),
 ('x_4_5', 90),
 ('x_4_6', 69),
 ('x_4_7', 1),
 ('x_5_1', 31),
 ('x_5_2', 93),
 ('x_5_3', 7),
 ('x_5_4', 90),
 ('x_5_6', 86),
 ('x_5_7', 59),
 ('x_6_1', 69),
 ('x_6_2', 24),
 ('x_6_3', 72),
 ('x_6_4', 69),
 ('x_6_5', 86),
 ('x_6_7', 81),
 ('x_7_1', 50),
 ('x_7_2', 5),
 ('x_7_3', 67),
 ('x_7_4', 1),
 ('x_7_5', 59),
 ('x_7_6', 81)]
OBJECTIVE_SENSE = 'minimize'


def build_model(data: dict) -> tuple:
    model = gp.Model()
    model.Params.OutputFlag = 0
    variables = {}
    type_map = {"C": GRB.CONTINUOUS, "I": GRB.INTEGER, "B": GRB.BINARY}
    for spec in VARIABLE_SPECS:
        kwargs = {"vtype": type_map[spec["vtype"]], "name": spec["name"]}
        if spec["lb"] is not None:
            kwargs["lb"] = spec["lb"]
        else:
            kwargs["lb"] = -GRB.INFINITY
        if spec["ub"] is not None:
            kwargs["ub"] = spec["ub"]
        variables[spec["name"]] = model.addVar(**kwargs)

    for spec in CONSTRAINT_SPECS:
        expression = gp.quicksum(coefficient * variables[name]
                                 for name, coefficient in spec["terms"])
        if spec["sense"] == "<=":
            model.addConstr(expression <= spec["rhs"], name=spec["name"])
        elif spec["sense"] == ">=":
            model.addConstr(expression >= spec["rhs"], name=spec["name"])
        else:
            model.addConstr(expression == spec["rhs"], name=spec["name"])

    objective = gp.quicksum(coefficient * variables[name]
                            for name, coefficient in OBJECTIVE_TERMS)
    model.setObjective(objective, GRB.MAXIMIZE if OBJECTIVE_SENSE == "maximize"
                       else GRB.MINIMIZE)
    return model, variables


def solve(data: dict) -> dict:
    model, variables = build_model(data)
    model.optimize()
    status_map = {
        GRB.OPTIMAL: "OPTIMAL",
        GRB.INFEASIBLE: "INFEASIBLE",
        GRB.UNBOUNDED: "UNBOUNDED",
        GRB.INF_OR_UNBD: "INF_OR_UNBD",
        GRB.TIME_LIMIT: "TIME_LIMIT",
    }
    status = status_map.get(model.Status, str(model.Status))
    if model.SolCount <= 0:
        return {"status": status, "objective": 0.0, "solution": {}}
    solution = {name: float(variable.X) for name, variable in variables.items()}
    return {"status": status, "objective": float(model.ObjVal), "solution": solution}
